### PR TITLE
A fix for #77

### PR DESCRIPTION
**Pull request by crazecoder**
```dart
double _scale = _getScale();
await FlutterImageCompress.compressAndGetFile(
    _file.absolute.path,
    _path,
    minWidth: _isLandscape ? 1920 : 1080,
    minHeight: _isLandscape ? 1080 : 1920,
    inSampleSize: _scale.toInt(), //scale to 1/_scale
    quality: 88,
);
```

### CODE REVIEW

**Comment by CaiJingLong** [comment]
Two problem:

1. Can you add inSampleSize of `compressWithList`? If you don't, I can add this part of code.
2. Is there an implementation in ios?

**Comment by CaiJingLong** [comment]
This is just a question, if not, I will merge this part to master branch.

**Comment by crazecoder** [comment]
Just for Android, I will add inSampleSize to compressWithList, but it is currently busy, so I think it would be better for you to add

**Comment by CaiJingLong** [comment]
OK, I will add it. thanks for pr.

**Pull request merged**
