### PR TITLE
Update Kotlin version

### PR DESCRIPTION
**Pull request by scascante**
This version just updates the Kotlin version for the compiler. I had issues trying to compile an Android App that uses this library because of it.

### CODE REVIEW

**Comment by CaiJingLong** [comment]
@scascacha 
I tried to set the version of Kotlin to 1.2.71 or 1.2.50 in an app dependency, and referenced the library. There was no compile / run failure. You might need to describe your error in detail, or send a gradle log / run log.
I can try to help you solve the problem.

**Comment by scascante** [comment]
When I run 'flutter build apk' on an App that I'm building I get this error:

`FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.2.51 and higher. Project 'flutter_image_compress' is using version 1.2.30.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s
`

**Comment by scascante** [comment]
@scascacha is an account that I can't access anymore, just in case you're wondering @CaiJingLong

**Comment by CaiJingLong** [comment]
I update some config and will use a new pr to update kotlin version.
#11

**Comment by scascante** [comment]
Awesome! Thanks!! I'm glad it worked!

**Pull request closed without merging**
